### ISSUE TITLE
Exceptions to numeric character references

### ISSUE THREAD

**Issue by mindplay-dk** [alwinb/tiny-html-lexer#3]
Can you explain what this is about?

https://github.com/alwinb/tiny-html-lexer/blob/ec1be861756d3305fe53ca67fb6c71c5c51dea8a/lib/token-builder.js#L117-L119

I'm not aware of any exceptions from the Unicode standard and couldn't find any information on it.

Perhaps it would be a good idea to add a link to the standard clause, as a comment in the source-code?

**Comment by alwinb** [comment]
This is [an exception][1] made in the HTML Standard for these particular numeric character references.
I think the reason for this is that they correspond to the C1-contol codepoints in the Latin-1 supplement block, which I assume have no graphical presentation in Unicode and are therefore decoded according to some extended-ASCII encoding for legacy reasons. I'm not sure which extended-ASCII encoding it is though. 

[1]: https://html.spec.whatwg.org/multipage/parsing.html#numeric-character-reference-end-state

**Comment by alwinb** [comment]
I found the encoding, it is [Windows-1252]

[Windows-1252]: https://en.wikipedia.org/wiki/Windows-1252

**Comment by alwinb** [comment]
[Done][1]!

[1]: https://github.com/alwinb/tiny-html-lexer/blob/5e96454caf70ee72b20553a031765fe80bc4fa4c/lib/token-builder.js#L116-L118
