### ISSUE TITLE
Line/column numbers in tokens

### ISSUE THREAD

**Issue by mindplay-dk** [alwinb/tiny-html-lexer#4]
For my use-case, I need line/column-numbers in the tokens.

I see the lexer has this feature (part of the reason I like this library) but it's unused by the tokenizer.

The tokenizer is a small piece of code, so I'm comfortable just to copy/modify as needed for my use-case - but, if you prefer, I could also submit a pull-request with this feature addition.

It will have a slight performance and memory impact - so I figured I'd ask first, if this is a feature you'd want?

**Comment by alwinb** [comment]
The stream state has three properties that you can use for this: line, position and lastnl -- the latter is the position of the last newline. So you can create a simple iterator transformer like so, to emit tokens (eh, 'chunks') with line numbers. It was another exercise in minimalism :)

```javascript
function* annotatedChunks (sample) {
  let stream = tinyhtml.chunks (sample)
  let  { position, line, lastnl } = stream.state
  for (let chunk of stream) {
    yield [{ line, col:position - lastnl }, chunk];
    ({ position, line, lastnl } = stream.state)
  }
}
```

**EDIT** 
- Ah, I see (just quickly now) that it doesn't work for tokens (as opposed to 'chunks'), so I need to check that. 
- I see that I already added a 'col' getter on stream.state so you can just use that in the code above.

**Comment by alwinb** [comment]
I will add this sometime soon though :)

**Comment by alwinb** [comment]
Added in v1.0.0-rc.2

```javascript
let stream = tinyhtml.tags ('<span>Hello, world</span>')
console.log (stream.state) // lexer state before
for (let token of stream) {
  console.log (token)
  console.log (stream.state) // lexer state after last seen tag 
}
```

Feel free to reopen, or to create a new issue if I've missed something!
