### ISSUE TITLE
ReferenceError: Cannot access 'parseNamedCharRef' before initialization

### ISSUE THREAD

**Issue by hyrious** [alwinb/tiny-html-lexer#6]
https://github.com/alwinb/tiny-html-lexer/blob/9dad145a51f11e121ccec0166796127c6095c805/lib/index.js#L8

Raised at `parseNamedCharRef = parseNamedCharRef`.

Node version: 16.13.0
OS: Windows 10

**Comment by alwinb** [comment]
Thank you! What a clumsy mistake. I’ll make a new version.

**Comment by alwinb** [comment]
I published version 1.0.0-rc.3 which should solve this issue.

Thank you again for catching this and filing the issue.
